

use soccer;
CREATE VIEW StadiumsInfo AS 
select c.club_name, s.std_name, l.lg_name, cn.country_name from stadium as s, club as c, league as l, country as cn
 where s.club_id in (select club_id from club) and c.lg_id in (select lg_id from league)
 and l.country_id in (select country_id from country);

 CREATE VIEW CountriesWonAtHome AS
SELECT W.WC_YEAR, C.COUNTRY_NAME FROM WORLDCUP AS W, COUNTRY AS C 
WHERE WINNING_COUNTRY_ID=HOST_COUNTRY_ID AND W.HOST_COUNTRY_ID=C.COUNTRY_ID;

CREATE VIEW WIN_PERCENT AS
SELECT CLUB_RANK, CLUBNAME, (CLUB_WINS*100/CLUB_PLAYED_MATCHES)AS PERCENTAGE FROM CLUB_STATS;

CREATE VIEW EACHCLUBMAXANDMINWINPERCENT AS
SELECT A.CLUB_NAME, B.MAXWIN, B.MINWIN
FROM (SELECT CLUB_NAME, CLUB_ID FROM CLUB)AS A INNER JOIN 
(SELECT CLUB_ID,MAX(CLUB_WINS*100/CLUB_PLAYED_MATCHES)AS MAXWIN,
MIN(CLUB_WINS*100/CLUB_PLAYED_MATCHES)  AS MINWIN FROM CLUB_STATS GROUP BY CLUB_ID)AS B
ON A.CLUB_ID=B.CLUB_ID;


CREATE VIEW CLUB_MINRANK_AND_MAXRANK AS
SELECT A.CLUB_NAME, B.MAXRANK, B.MINRANK
FROM (SELECT CLUB_NAME, CLUB_ID FROM CLUB)AS A
INNER JOIN
(SELECT CLUB_ID, MAX(CLUB_RANK)AS MINRANK, MIN(CLUB_RANK) AS MAXRANK FROM CLUB_STATS GROUP BY CLUB_ID)AS B
ON A.CLUB_ID=B.CLUB_ID;
